export const WHEEL_ITEM_HEIGHT = 40;
export const WHEEL_VISIBLE_ITEMS = 5;
export const WHEEL_HEIGHT = WHEEL_ITEM_HEIGHT * WHEEL_VISIBLE_ITEMS;
export const WHEEL_OFFSET = WHEEL_HEIGHT / 2 - WHEEL_ITEM_HEIGHT / 2;